apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB65p+IULGNPCMWu9vNDoShmEVKRko855diomlz2ngBl8s08ui8ExV5QnfbDrFee5OcxQTMu0UOo1QWz0HfnnT89lMtBv+GDVYvJBnA4BspyYfY+viC9D73SGeC/wUR6mvMRkG5NYNsfzxKOXGJV4eQOnfkwXV0FRZXOWUfgBhFi5vDbZ0BX+eK0HQUaQhk/q8TrjNAr6IzE4psmHP95rtgHxoLgpnm0JmJ8vd7UAeqA/Dcaj9PFemJiyK/mRyBlQKNZpJKFIrr1l8tc4PAR2dOz9VLpsRkB2K7usNycOEW0emT5IZnV8GTdqHD6eix+cHz3hvg8U7palMw3jTvLKDGJAky4yeeS3JT+1VtfPEqEX4NgVAKixlIk2fwncLSFi2SBJfiZ6+3ZFZujLiPiu0EzHDgmUEplz2gv5wYUGuwQXnkcGYku5RDNUajB3AnSWylFd+yq5hz4+SdJDAcDjid0iYz/jCnsmhW+q8BEw9KSYkfDoyUX7/Y2TT9GzPPn4oezrGRygNT2cWeTL5UA03qIajNPneWRi3gM8WAN7m7IWaqWyaktrGI9dWVXf7lodbCbFIzTXdpo00Rr2YxM8hmRU0QPumn+fdAS78ZcsQSd7f5CkFeBz7QVWFqUgfL9I11er+mc/ACmHWLELAFE3rEeO5pRIly/SxQ6QNH7X5AWOF7+ugYPLTmDBOCa7uzGd/jZfS3VdB2VW+ZVMgQYLDoVKX2LL5DSGk3g0LmIOMWbPaorWDNjdji+6d40QDAsId1yJnChwr/47OMa5+m5b4yyHlCVWYdas/luHDz7hqcVIg5lopHVHEFhwiTVWaX0I5eq9UL7IvxCaN8fzsjQhRq6rpcEE2uDG7fyF47O3k0uT10OSy7ZWm8mPM=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
