apiVersion: v1
kind: Secret
metadata:
  name: github.service-account-token
  annotations:
    kubernetes.io/service-account.name: github
type: kubernetes.io/service-account-token
  
  
  ARGO_TOKEN="Bearer $(kubectl get secret jenkins.service-account-token -o=jsonpath='{.data.token}' | base64 --decode)"
  echo $ARGO_TOKEN
  Bearer ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltS...
  
  kubectl create role jenkins --verb=list,update --resource=workflows.argoproj.io
