apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: c0de-ch-admin-role
  namespace: argo
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - workflows/finalizers
    - cronworkflows
    - cronworkflows/finalizers
    - workfloweventbindings
    - workfloweventbindings/finalizers
    - workflowtaskresults
    - workflowtaskresults/finalizers
    - workflowtasksets
    - workflowtasksets/finalizers
    - workflowtasksets/status
    - workflowtemplates
    - workflowtemplates/finalizers
    - eventsources
    - sensors
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - deletecollection
    - delete