apiVersion: v1
kind: Secret
metadata:
  name: private-c0de-argo-pipeline-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/c0de-ch/argo-pipeline.git
  password: Z2l0aHViX3BhdF8xMUJFVzdaTUEwbzhJT0psYUIxMng1X09XbHU0bHBWcWgxRHVJbVZVVDQxWmxkWVg3MFFQY3NyM082eng4b01SdEpLTFpDRFE0VU1FVUFOYnRn
  username: github
