apiVersion: v1
kind: Secret
metadata:
  name: private-c0de-argo-pipeline-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/c0de-ch/argo-pipeline.git
  password: Z2l0aHViX3BhdF8xMUJFVzdaTUEwd3N2QVJnYm9mUTFuXzN2NjdvaGNUVE1icjl6QUVlblIySzdVZDBidGpaVU9McENQeHJmSEJGWURTNTVPQ1dERTlRS1U0ZkozCg==
  username: github
