apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server2
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem