apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv010
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.78.97
    path: "/mnt/pool001/k8s-pv010"
